### ISSUE TITLE
components目录下无效

### ISSUE THREAD

**Issue by jetBn** [dcasia/mini-program-tailwind-webpack-plugin#1]

**Comment by ItsRyanWu** [comment]
无效具体指的是什么？你可以提供一下复现案例吗？我在本地仓库无法复现

**Comment by jetBn** [comment]
![image](https://user-images.githubusercontent.com/26957220/159893985-4f792cac-91fc-49d7-a75b-d87cec4ad0d2.png)
<img width="475" alt="image" src="https://user-images.githubusercontent.com/26957220/159894234-6f422ee7-ced7-4e61-a09d-e0ee75cd5bb6.png">

没有生效  就example 目录下

**Comment by jetBn** [comment]
![image](https://user-images.githubusercontent.com/26957220/159894340-d1356d4c-10a6-4ffb-8c25-33c4b34a6339.png)

**Comment by ItsRyanWu** [comment]
@jetBn 我检查了下，这其实是一个小程序的限制，若要想让组件可以被 tailwind/windi 生产的 CSS 作用到，需要在该组件的 JSON 配置文件中将 `styleIsolation` 选项设置为 `shared` 或者 `apply-shared`。
在 MPX 中的具体示例为：
```HTML
<script type="application/json">
  {
    "component": true,
    "styleIsolation": "shared"
  }
</script>
```
这是一个很好的问题，我会在文档中更新该注意事项。

**Comment by 3lang3** [comment]
@ItsRyanWu  taro react 项目中，非pages目录无效，如何设置 `styleIsolation` 属性呢？

**Comment by ItsRyanWu** [comment]
> @ItsRyanWu  taro react 项目中，非pages目录无效，如何设置 `styleIsolation` 属性呢？

Taro 这个案例需要根据你的 repo 具体分析，和 `styleIsolation` 无关，如果确保使用了 `jsx`/`tsx` 后缀还是出现问题，请提供一下复现案例并创建新的 issue，谢谢。

**Comment by 3lang3** [comment]
> > @ItsRyanWu  taro react 项目中，非pages目录无效，如何设置 `styleIsolation` 属性呢？
> 
> Taro 这个案例需要根据你的 repo 具体分析，和 `styleIsolation` 无关，如果确保使用了 `jsx`/`tsx` 后缀还是出现问题，请提供一下复现案例并创建新的 issue，谢谢。

#43
