### ISSUE TITLE
使用vscode开发没有tailwindcss的代码提示

### ISSUE THREAD

**Issue by yuuko-1410** [dcasia/mini-program-tailwind-webpack-plugin#100]
**描述这个问题：**
使用这个插件可以很方便的使用Tailwindcss，但并没有样式自动提示，写起来很没有安全感。请问这个有办法可以解决吗
**开发框架版本（三选一填写）：**
 - Taro: 3.6.6

**Comment by tylerrrkd** [comment]
https://marketplace.visualstudio.com/items?itemName=voorjaar.windicss-intellisense
