### ISSUE TITLE
偶现类名失效，app.wxss里没有对应类名

### ISSUE THREAD

**Issue by parabolazz** [dcasia/mini-program-tailwind-webpack-plugin#102]
**描述这个问题：**
偶尔会出现app.wxss没有打出任何类名的情况，且一旦出现就很难再恢复正常。
对应的windi配置：
```
// windi.config.js
export default {
  prefixer: false,
  extract: {
    // 忽略部分文件夹
    exclude: ['node_modules', '.git', 'dist'],
    include: ['src'],
  },
  corePlugins: {
    // 禁用掉在小程序环境中不可能用到的 plugins
    container: false,
  },
};

```

**如何复现：**
使用taro最新版本，开发了几天之后出现的，没有正常的复现渠道

**期待的结果：**

类名正常显示

**问题相关截图：**

![image](https://github.com/dcasia/mini-program-tailwind/assets/17560446/6a05f223-f830-4193-821d-556321d57ae9)

**本插件版本：**
1.5.6

**开发框架版本（三选一填写）：**
 - Taro:

**其余信息：**

**Comment by tylerrrkd** [comment]
+1 偶现问题，很难复现。有大佬知道怎么解决吗？

**Comment by parabolazz** [comment]
我现在已经完全用不了了

> +1 偶现问题，很难复现。有大佬知道怎么解决吗？

**Comment by tylerrrkd** [comment]
> 我现在已经完全用不了了
> 
> > +1 偶现问题，很难复现。有大佬知道怎么解决吗？

那你怎么解决呢 有什么替代方案吗

**Comment by ItsRyanWu** [comment]
@tylerrrkd @parabolazz  请升级至 `1.5.7-beta.0` 试试看呢？如果没有问题我就发布正式版了

**Comment by tylerrrkd** [comment]
> @tylerrrkd @parabolazz 请升级至 `1.5.7-beta.0` 试试看呢？如果没有问题我就发布正式版了

项目赶时间 已经换成别的方案了 抱歉

**Comment by parabolazz** [comment]
<img width="1191" alt="image" src="https://github.com/dcasia/mini-program-tailwind/assets/17560446/48f11b0b-16fe-45c1-b764-b0bb50f31716">
<img width="950" alt="image" src="https://github.com/dcasia/mini-program-tailwind/assets/17560446/eaa52c73-301c-4595-ae83-3e5b55c88b53">
不好意思，更新了之后还是木有生效
