### ISSUE TITLE
bg-[#1636fc] 和其他class一起用，其他样式失效

### ISSUE THREAD

**Issue by cat-kun** [dcasia/mini-program-tailwind-webpack-plugin#103]
**描述这个问题：**

bg-[#1636fc] 和其他class一起用，其他样式失效（横杆多了空格）

**如何复现：**

```tsx
<Button className="bg-[#1636fc] border-[#1636fc] text-[#fff] text-[24px] text-center rounded-[80px] w-[180px] h-[48px] leading-[48px] mt-[40px]">按钮</Button>
```

**期待的结果：**

其他样式正常编译

**问题相关截图：**

![image](https://github.com/dcasia/mini-program-tailwind/assets/8529528/99072544-8faf-4f5d-9d97-3f2d00162455)

**本插件版本：**

1.5.6

**开发框架版本：**
 - Taro 3.5.11

**Comment by ItsRyanWu** [comment]
请升级至 `1.5.7-beta.0` 试试看呢？如果没有问题我就发布正式版了

**Comment by Murphy-Tong** [comment]
确实是有这个问题
