### ISSUE TITLE
带特殊符号([].!/)的样式没有正确转换，导致失效

### ISSUE THREAD

**Issue by jhxlhl1023** [dcasia/mini-program-tailwind-webpack-plugin#105]
**描述这个问题：**
存在部分文件的编译结果没有将 className 的特殊符号转换，原因已查明。
即：扫描和收集 rawVsModifiedPairs 的顺序，和 compilation.hooks.afterOptimizeAssets.tap 的 assets 顺序不一定一致
导致本应用于替换 文件A 的 pair，被用于替换了 文件B，造成替换结果混乱。
如：
文件A: className: "w-full p-[24px] m-[24px]" => 转换错误，不完全转换 "w-full p--24px- m-[24px]"
文件B: className: "w-full p-[24px]" => 转换错误，无变化

**如何复现：**
文件A: className: "w-full p-[24px] m-[24px]"
文件B: className: "w-full p-[24px]"

**期待的结果：**
文件A: className: "w-full p--24px- m--24px-"
文件B: className: "w-full p--24px-"

**问题相关截图：**
由于 rawVsModifiedPairs 匹配错乱，这里剩余了一些无法匹配的项。
![image](https://github.com/dcasia/mini-program-tailwind/assets/42853646/c05f2eae-a921-4c80-9af2-8a44f2801688)

**本插件版本：**
1.5.6

**开发框架版本（三选一填写）：**
 - Taro: 3.4

**其余信息：**

**Comment by ItsRyanWu** [comment]
谢谢 debug, 正在处理

**Comment by ItsRyanWu** [comment]
请升级至 `1.5.7-beta.0` 试试看呢？如果没有问题我就发布正式版了

**Comment by jhxlhl1023** [comment]
经过测试是可以修复问题。

不过我想法是将 rawVsModifiedPair 根据 key.length 倒序来解决匹配错乱的问题~
先长后短，应该就不会错乱了，暂且把想法放在这里，没试过，不知道可不可行。
```js
rawVsModifiedPair.sort(([key0], [key1]) => key1.length - key0.length);
```

**Comment by ItsRyanWu** [comment]
> 经过测试是可以修复问题。
> 
> 不过我想法是将 rawVsModifiedPair 根据 key.length 倒序来解决匹配错乱的问题~ 先长后短，应该就不会错乱了，暂且把想法放在这里，没试过，不知道可不可行。
> 
> ```js
> rawVsModifiedPair.sort(([key0], [key1]) => key1.length - key0.length);
> ```

这似乎是一种更简单奏效的思路。我目前的方案是根据引号的开始和结束做了严格的开头至结尾的匹配，所以应该可以防止出现匹配错乱的问题了。
