### ISSUE TITLE
请问一下是如何实现的任意 fraction

### ISSUE THREAD

**Issue by kosuke-zhang** [dcasia/mini-program-tailwind-webpack-plugin#107]
比如 tailwind 没有 z-21，但是在您的框架之下直接使用 z-21 也是可以支持的，请问这个任意的数值是如何实现的呀？

**Comment by kosuke-zhang** [comment]
可以通过 z-[21] 来实现相同的任意数值的功能，查了一下这个是通过 JIT 模式实现的，但是对于我来说多加个 [] 还是比较麻烦，请问本框架是如何实现 z-21 使用 JIT 模式的呀？

**Comment by ItsRyanWu** [comment]
这个是 Windi CSS 的功能，具体可以查看它的文档哦
