### ISSUE TITLE
能否支持Uniapp的开发模式？也是用来开发微信小程序

### ISSUE THREAD

**Issue by tiehumobilenow** [dcasia/mini-program-tailwind-webpack-plugin#11]
麻烦问下，能否支持Uniapp的开发模式？
也是用来开发微信小程序
另外，好像Windicss只支持Vue3吧？

**Comment by ItsRyanWu** [comment]
我看一下，Windi CSS 不局限于前端框架。

**Comment by tiehumobilenow** [comment]
谢谢回复，希望能支持VUE2的uniapp开发小程序， 用于生产环境， 强烈期待中

**Comment by ItsRyanWu** [comment]
uni-app Vue 2 安装说明文档已更新：[uni-app 小程序](https://www.craft.do/s/Wx2f9cjGwyZYOx/b/B678DA14-91F0-4483-8D4C-F7EE7EBB3B11/%F0%9F%94%97_uni-app_%E5%B0%8F%E7%A8%8B%E5%BA%8F)
uni-app Vue 3 下一阶段会适配

**Comment by tiehumobilenow** [comment]
感谢，先试试，有问题再来反馈！
