### ISSUE TITLE
是否不支持.shadow-red-500\/50这样的写法

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [dcasia/mini-program-tailwind-webpack-plugin#16]
是否不支持.shadow-red-500\/50这样的写法? 测试会报错

**Comment by ItsRyanWu** [comment]
```html
<view class="shadow-lg shadow-red-500/50"/>
```
对于以上案例我测试没有问题，可以正常显示样式。
至于标题里的 `shadow-red-500\/50` 我不是很明白为什么在这里要手动加一个 `\` 在 `/50` 之前？这应该是在你那边无法正常工作的原因。

**Comment by liuhuapiaoyuan** [comment]
感谢回复~
看windicss的文档给误导
![111111111](https://user-images.githubusercontent.com/8020726/170881865-bbf0f762-7cc9-4215-964f-0c83173e1d93.png)
了
