### ISSUE TITLE
space-x 在开启 taro 压缩后异常

### ISSUE THREAD

**Issue by BoneTM** [dcasia/mini-program-tailwind-webpack-plugin#21]
![image](https://user-images.githubusercontent.com/48622532/173807176-60d6cda6-686a-42c1-907c-117834a57a01.png)
![image](https://user-images.githubusercontent.com/48622532/173807192-2ffdeddc-8c77-4b23-a8e7-5a64536738f2.png)
上图为压缩后
下图为压缩前

**Comment by BoneTM** [comment]
然后小程序就直接报错了

**Comment by ItsRyanWu** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/17338101/173871930-8591fd2b-4243-45a8-bcea-3975271745de.png">
想确认下你是不是用了这个功能？

**Comment by BoneTM** [comment]
应该没有 我是taro 3.4

**Comment by BoneTM** [comment]
![image](https://user-images.githubusercontent.com/48622532/173881247-a3eaf882-0738-4979-bbb5-17020502aa5a.png)
![image](https://user-images.githubusercontent.com/48622532/173881299-d2dc65fe-7ce3-423b-a6fa-e41d61a9f9ee.png)
而且压缩后 带小数点的 rem to rpx 也失效了，不压缩的情况下 工作良好

**Comment by BoneTM** [comment]
我就是单纯的build:weapp之后 就会这样，感觉可能需要在压缩之前处理rem to rpx

**Comment by ItsRyanWu** [comment]
感谢反馈这些问题，请升级至 `1.4.2` 获取修复。

**Comment by xinjie16** [comment]
w-1/2 这样的class也会在压缩后失效，需要用绝对值，类似w-100
