### ISSUE TITLE
taro example 似乎跑不起来 Cannot property 'platform' of undefined

### ISSUE THREAD

**Issue by byteHulk** [dcasia/mini-program-tailwind-webpack-plugin#23]
dcasia/mini-program-tailwind-webpack-plugin/dist/taro.js: 539:40
这里似乎配置的路径不对 难道和 taro 的版本升级有关系？

**Comment by ItsRyanWu** [comment]
插件会通过 Taro 提供的插件 API `ctx.runOpts.options.platform` 获取目前程序是向哪个平台编译的，我搜了下这个 API 是从 Taro 2.2 以后引入的，难道你用的 Taro 比这个版本还低？你的 Taro 版本是多少呢？是否可以提供一个复现问题的 demo？

**Comment by byteHulk** [comment]
"@tarojs/taro": "3.4.9" 是仓库提供的 example ，你那边可以跑起来吗，我试了一下改成 ctx.runOpts.platform 似乎就对了

**Comment by ItsRyanWu** [comment]
不应该呀，这是我用目前最新的版本 `3.4.12` 加上 React example 测试的结果
```javascript
// ctx.runOpts
{
  _: [ 'build' ],
  options: {
    platform: 'weapp',
    // ...
  },
  isHelp: false
}
```
`ctx.runOpts.options.platform` 的路径是正确的，开发的时候是基于 `3.4.9` 测试的，现在是基于 `3.4.12` 测试的，都没成功复现你说的这个问题。
你是用什么命令运行运行的？有没有可能由于你本地全局的 Taro 版本太旧了？

**Comment by byteHulk** [comment]
本地全局 taro 版本是 3.0.23 ，看起来确实是这个导致的 可能文档得更新一下？

**Comment by ItsRyanWu** [comment]
请问你将 CLI 版本与项目内的依赖版本对齐后还会出现问题吗？
另外，对于你说的文档要不要更新的问题，其实 Taro 的文档已经提到了该[注意事项](https://taro-docs.jd.com/taro/docs/GETTING-STARTED#%E4%BF%9D%E6%8C%81-cli-%E7%9A%84%E7%89%88%E6%9C%AC%E4%B8%8E%E5%90%84%E7%AB%AF%E4%BE%9D%E8%B5%96%E7%89%88%E6%9C%AC%E4%B8%80%E8%87%B4)，如果我在插件的文档里提及可能会有些冗余和重复
![image](https://user-images.githubusercontent.com/17338101/174770072-3fdaf234-0bf6-4ae8-94bd-11c7df46f508.png)
