### ISSUE TITLE
【Taro】开启 Preact 后，部分能力失效

### ISSUE THREAD

**Issue by jay4q** [dcasia/mini-program-tailwind-webpack-plugin#24]
根据 [Taro官方文档](https://taro-docs.jd.com/taro/docs/next/preact/) 在 [示例代码](https://github.com/dcasia/mini-program-tailwind/tree/development/examples/taro/react) 中添加 preact 并运行工程后，控制台提示 `[mini-program-tailwind-plugin]: Unsupported framework type` ，能正常进行下去，不过如 Fraction、Value infer 等能力均失效了。例如编写 `className='text-[#ffffff]'` 最终编译成 `className='text- ffffff'`

**Comment by ItsRyanWu** [comment]
插件目前还未支持 Preact 框架，这周我会研究一下并适配。

**Comment by ItsRyanWu** [comment]
请升级至 `1.4.3` 获取对使用 Preact/compat 的兼容
