### ISSUE TITLE
mr-2.5 这种写法是不是不支持了呀

### ISSUE THREAD

**Issue by coderlfm** [dcasia/mini-program-tailwind-webpack-plugin#26]
`mr-2.5` 被转换成了 `mr-2 5` 两个类名
而且 `mt-[450px]` 也转换成了 `mt- 450`，需要写成 `mt-450px`才有效
目前体现在trao react 最新的版本中

**Comment by ItsRyanWu** [comment]
目前对 React 仅支持对 .jsx 或 .tsx 文件的解析，如果你已经使用了以上后缀还是出现问题，请提供一个可以复现的 repo，谢谢。

**Comment by coderlfm** [comment]
https://github.com/coderlfm/taro-little-bear 这个仓库就可复现

**Comment by coderlfm** [comment]
我尝试了一下，回退到 taro 3.4.13 版本后转换正常

**Comment by ItsRyanWu** [comment]
> 我尝试了一下，回退到 taro 3.4.13 版本后转换正常

好的，我研究下对 Taro 3.5 beta 的适配

**Comment by ItsRyanWu** [comment]
请升级至 `1.5.2` 获取支持
