### ISSUE TITLE
mpx的demo都运行不起来

### ISSUE THREAD

**Issue by joezhang-sh** [dcasia/mini-program-tailwind-webpack-plugin#28]
![image](https://user-images.githubusercontent.com/4892632/176983666-07d1e51a-e679-41d2-939d-28b9bdaf787f.png)

**Comment by ItsRyanWu** [comment]
请问你本地的 MPX 版本是否大于等于 2.7.5？这个版本之前的 MPX 有一个 bug 导致无法使用插件

**Comment by joezhang-sh** [comment]
之前确实不是，官方cli装的2.7.1，现在更新成2.7.37也是一样的错误
![image](https://user-images.githubusercontent.com/4892632/177000367-3b481165-0514-4974-8b42-f1ee41d8d9cd.png)

**Comment by ItsRyanWu** [comment]
我这边也同样升级至相应的版本没有成功复现，请把你的 repo 上传我来看看

**Comment by joezhang-sh** [comment]
> 我这边也同样升级至相应的版本没有成功复现，请把你的 repo 上传我来看看

我是把这个项目的repo拉下来，然后直接在samples/mpx下install后运行的，我回头删了modules再重新install一下

**Comment by ItsRyanWu** [comment]
> > 我这边也同样升级至相应的版本没有成功复现，请把你的 repo 上传我来看看
> 
> 
> 
> 我是把这个项目的repo拉下来，然后直接在samples/mpx下install后运行的，我回头删了modules再重新install一下

我也是这样做的...

**Comment by perchecc** [comment]
### 你好，我也遇到了同样的问题，插件运行不起来
#### 具体问题是：
在我自己的项目中使用您的webpack插件，并按照教程配置了，但是mpx打包输出的wx目录文件无法在微信开发者工具运行起来。

错误如下：

![image](https://user-images.githubusercontent.com/17824405/180654293-bb7ff66c-57e6-480a-8b32-d07d6ae318b6.png)

我本来以为是我的mpx项目配置影响，于是参考了[集成案例](https://github.com/dcasia/mini-program-tailwind/tree/development/examples/mpx),并修改了mpx相关依赖版本为`    "@mpxjs/api-proxy": "^2.7.28",
    "@mpxjs/core": "^2.7.37",`，其他的代码均为变动。然后，我又使用了yarn工具下载了依赖，没有任何问题，项目`npm run watch`命令也运行正常。但是最终输出的wx目录文件也无法正常运行，报错也基本相同，如下：

![image](https://user-images.githubusercontent.com/17824405/180654447-8f4241dd-0733-45a3-9b40-fa3f93090d52.png)

希望帮忙处理一下，谢谢~

#### [集成案例改动后的demo repo链接](https://gitee.com/ackmaneva/windicss-demo.git)

#### 开发环境
- 微信开发者工具基础库版本 
![image](https://user-images.githubusercontent.com/17824405/180654690-c68159ab-de5a-4eb7-85ac-4962df69942e.png)
- 系统环境
windows 
```
版本	Windows 11 企业版
版本	21H2
安装日期	‎2022/‎6/‎9
操作系统版本	22000.795
体验	Windows 功能体验包 1000.22000.795.0

```
#### 备注
上传案例的dist/wx目录是我测试后的输出目录，也可以直接在微信开发者工具尝试运行

**Comment by ItsRyanWu** [comment]
@ackemaneva 感谢你提供的详细线索，鉴于你是 Windows 开发环境那我怀疑和 Windows 不支持文件名中包含 `:` 字符有关，详情请参考： #4
