### ISSUE TITLE
热更新失效

### ISSUE THREAD

**Issue by transtone** [dcasia/mini-program-tailwind-webpack-plugin#3]
修改了值必须重新编译之后才能得到，没有了热更新。

**Comment by ItsRyanWu** [comment]
谢谢反馈，因为平时并不经常用开发者工具里的“热重载”功能所以并没有在意到这个问题。

经调查发现该问题是由于微信开发者工具不支持监听由 @import 引用的 wxss 样式文件内容变动的 bug 引起的，并且通过官方社区查询该 bug 相关信息发现[该 bug 在 2020 年时就已经存在](https://developers.weixin.qq.com/community/develop/doc/000222ed318d5031330b5abcf51c00?highline=%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7%E7%83%AD%E9%87%8D%E8%BD%BD)。

由于在小程序中使用 tailwind/windi css 的产物的最佳方式就是通过 @import 来引用一个单独的外部生成文件来做到样式文件的解耦，所以在官方有可能修复热重载功能之前该问题应该会一直存在，在此之前还是建议你关闭“热重载”而直接使用默认的全局重载。

**Comment by ItsRyanWu** [comment]
问题已再次反馈给官方员工，有望在下个版本的开发者工具修复。

<img width="620" alt="image" src="https://user-images.githubusercontent.com/17338101/165895290-f6e6c5bd-4a58-4d65-8709-e9fed2b174f4.png">

**Comment by ItsRyanWu** [comment]
@transtone 该 bug 已在微信开发者工具 Nightly 1.06.2205052 版本中修复
下载：http://dldir1.qq.com/WechatWebDev/test/cover/wechat_devtools_1.06.2205052_darwin_x64.dmg

**Comment by JIANGYUNPU** [comment]
> @transtone 该 bug 已在微信开发者工具 Nightly 1.06.2205052 版本中修复
> 下载：http://dldir1.qq.com/WechatWebDev/test/cover/wechat_devtools_1.06.2205052_darwin_x64.dmg

https://github.com/JIANGYUNPU/csmpx    按官方文档操作还是一样的不生效，开发者工具已经最新的了1.06.2205172

**Comment by ItsRyanWu** [comment]
> > @transtone 该 bug 已在微信开发者工具 Nightly 1.06.2205052 版本中修复
> > 下载：http://dldir1.qq.com/WechatWebDev/test/cover/wechat_devtools_1.06.2205052_darwin_x64.dmg
> 
> https://github.com/JIANGYUNPU/csmpx 按官方文档操作还是一样的不生效，开发者工具已经最新的了1.06.2205172

具体是什么不生效？我下载了[预览版 1.06.2205231](https://developers.weixin.qq.com/community/minihome/doc/0006ee9b000e00aca1fd53c5559c01) 使用热重载是生效的，配合插件使用起来没有问题。
另外我发现你在组件内使用 Windi CSS 但并未在组件 JSON 配置中声明：
```json
{
  "component": true,
  "styleIsolation": "apply-shared" // 声明 'apply-shared' 或 'shared'
}
```
https://github.com/JIANGYUNPU/csmpx/blob/master/src/components/list.mpx#L16
这会导致你的组件样式无法被 Tailwind/Windi CSS 生成的样式作用到。
关于这一点文档中有[特别提醒](https://github.com/dcasia/mini-program-tailwind#%E9%99%B7%E9%98%B1)，这是微信小程序对于组件样式的限制。
同类 issue: #1

**Comment by JIANGYUNPU** [comment]
> > > @transtone 该 bug 已在微信开发者工具 Nightly 1.06.2205052 版本中修复
> > > 下载：http://dldir1.qq.com/WechatWebDev/test/cover/wechat_devtools_1.06.2205052_darwin_x64.dmg
> > 
> > 
> > https://github.com/JIANGYUNPU/csmpx 按官方文档操作还是一样的不生效，开发者工具已经最新的了1.06.2205172
> 
> 具体是什么不生效？我下载了[预览版 1.06.2205231](https://developers.weixin.qq.com/community/minihome/doc/0006ee9b000e00aca1fd53c5559c01) 使用热重载是生效的，配合插件使用起来没有问题。 另外我发现你在组件内使用 Windi CSS 但并未在组件 JSON 配置中声明：
> 
> ```json
> {
>   "component": true,
>   "styleIsolation": "apply-shared" // 声明 'apply-shared' 或 'shared'
> }
> ```
> 
> https://github.com/JIANGYUNPU/csmpx/blob/master/src/components/list.mpx#L16 这会导致你的组件样式无法被 Tailwind/Windi CSS 生成的样式作用到。 关于这一点文档中有[特别提醒](https://github.com/dcasia/mini-program-tailwind#%E9%99%B7%E9%98%B1)，这是微信小程序对于组件样式的限制。 同类 issue: #1

不好意思不好意思，把这里拉下了。
