### ISSUE TITLE
taro 下 w-1/2 压缩编译后变成了w-1 2

### ISSUE THREAD

**Issue by brookyu** [dcasia/mini-program-tailwind-webpack-plugin#33]
如题，开发模式下效果完好，压缩后发生了变形

**Comment by ItsRyanWu** [comment]
你说的压缩是指 build 到生产环境时 Taro 自带的压缩？也就是 run `dev:weapp` 的时候正常，但是 run `build:weapp` 的时候不正常？如果是这样的话，我这边测试正常，无法成功复现这个问题。
请提供更具体的信息或 repo。

**Comment by brookyu** [comment]
这是在您提供sample的代码里简单加的w-1/2：
<img width="702" alt="image" src="https://user-images.githubusercontent.com/230621/177172540-567f92b0-c4a0-4114-9205-6ee38d2e0323.png">
这是运行npm run build:weapp 后微信开发者工具对应代码呈现：
<img width="653" alt="image" src="https://user-images.githubusercontent.com/230621/177172428-9db77758-268f-42e1-af85-be428fabf3db.png">

**Comment by brookyu** [comment]
我找到了原因，我在windi.config.ts 加了这些自定义width, 删掉就正常了，不知什么原因
```
width: {
                '1/2': '50%',
                '1/3': '33.33333%',
                '2/3': '66.66667%',
                '1/4': '25%',
                '2/4': '50%',
                '3/4': '75',
                '1/5': '20%',
                '2/5': '40%',
                '3/5': '60%',
                '4/5': '80%',
                '1/6': '16.66667%',
                '1/7': '14.286%',
                '5/6': '83.3333%',
                '9/10': '90%',
            },
```

**Comment by ItsRyanWu** [comment]
> 我找到了原因，我在windi.config.ts 加了这些自定义width, 删掉就正常了，不知什么原因
> 
> ```
> width: {
>                 '1/2': '50%',
>                 '1/3': '33.33333%',
>                 '2/3': '66.66667%',
>                 '1/4': '25%',
>                 '2/4': '50%',
>                 '3/4': '75',
>                 '1/5': '20%',
>                 '2/5': '40%',
>                 '3/5': '60%',
>                 '4/5': '80%',
>                 '1/6': '16.66667%',
>                 '1/7': '14.286%',
>                 '5/6': '83.3333%',
>                 '9/10': '90%',
>             },
> ```

需要继续深究其他原因，配置文件应该不是影响因素。一方面是因为我按照你说的这个配置并没有复现这个问题，另一方面是插件的主要工作原理和配置文件不存在联系。

**Comment by b1ngx** [comment]
同样遇到了这样的问题

![image](https://user-images.githubusercontent.com/2504871/177964124-428fd3f7-0780-4af0-9e80-0204137b47f7.png)

**Comment by ItsRyanWu** [comment]
> 同样遇到了这样的问题
> 
> ![image](https://user-images.githubusercontent.com/2504871/177964124-428fd3f7-0780-4af0-9e80-0204137b47f7.png)

你遇到的问题已在和该问题不属于同一类，已在 #35 中回复。

**Comment by b1ngx** [comment]
> 你说的压缩是指 build 到生产环境时 Taro 自带的压缩？也就是 run `dev:weapp` 的时候正常，但是 run `build:weapp` 的时候不正常？如果是这样的话，我这边测试正常，无法成功复现这个问题。 请提供更具体的信息或 repo。

@ItsRyanWu 这里有个复现 repo

https://github.com/b1ngx/taro-vue3-tailwind

**Comment by ItsRyanWu** [comment]
抱歉，来晚了。该问题已在 `1.5.1` 中被修复，请及时升级以获取支持。
由于 Vue 3 对 setup script build 时不会使用在 module 路径中标记 type=template 所以导致插件未处理该 module。
感谢 @b1ngx 提供线索。
