### ISSUE TITLE
taro vue3 特殊转义字符支持问题

### ISSUE THREAD

**Issue by b1ngx** [dcasia/mini-program-tailwind-webpack-plugin#35]
**问题如图：**

![image](https://user-images.githubusercontent.com/2504871/178093854-3cee58cf-6b32-43b0-830f-ee90cfe67dfa.png)

**技术栈：**
Taro + vue3

**最小重现：**
https://github.com/b1ngx/taro-vue3-tailwind

**Comment by ItsRyanWu** [comment]
感谢反馈，的确存在该 bug，正在研究中，争取这周修复。

**Comment by ItsRyanWu** [comment]
原因为插件此前未考虑到 Vue 3 compiler 会对已经预判为静态 VNode 的节点进行预字符串化，而被字符串化后的节点会直接采用 markup 字符串描述而非以对象的形式，但插件目前并未解析该 markup。

**Comment by ItsRyanWu** [comment]
请升级至 `1.4.5` 获取支持

**Comment by b1ngx** [comment]
赞👍

**Comment by b1ngx** [comment]
taro build 后仍存在这个问题

https://github.com/b1ngx/taro-vue3-tailwind

**Comment by ItsRyanWu** [comment]
> taro build 后仍存在这个问题
> 
> https://github.com/b1ngx/taro-vue3-tailwind

感谢你的反馈，这个问题是由新的原因导致的。Vue 3 对 setup script build 时不会使用在 module 路径中标记 `type=template` 所以导致插件未处理该 module。
该问题在 `1.5.1` 中被修复，请及时升级获取支持。
