### ISSUE TITLE
vue3+uniapp+unocss 0.44.1微信端出现的bug

### ISSUE THREAD

**Issue by zhoubapi999** [dcasia/mini-program-tailwind-webpack-plugin#38]
微信小程序端运行后app.wxss出现 * 选择器导致运行报错，以及不支持opacity-75这种写法

**Comment by ItsRyanWu** [comment]
造成该问题的原因是 Uno CSS 会将一些默认的工具类 CSS 变量通过 `*` 选择器预先设置到每一个元素上以便后续使用，但小程序环境不支持 `*` 选择器。
我打算采用的解决方案是将 `*` 替换为所有小程序自带的组件名称，并新增一个设置项 `utilitiesSettings.customComponents` 用来增加除了小程序自带组件之外其余的自定义组件名称，这样也让自定义组件被 Uno CSS 正常作用到。

**Comment by ItsRyanWu** [comment]
请升级至 `1.5.0` 获取支持
