### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by PresByter2015** [dcasia/mini-program-tailwind-webpack-plugin#39]
使用 
`taro build --type weapp`
打包
下面是bug内容

> 
\ 正在编译...[mini-program-tailwind-plugin]: Class names collection benchmark 0ms
| 正在编译...[mini-program-tailwind-plugin]: Collected []
[mini-program-tailwind-plugin]: Class names replacement benchmark 0ms
�🙅  编译失败败. 2022/7/14 13:20:

./src/pages/test/index.vue) 1:0
Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/@tarojs/taro-loader/lib/raw.js
 * ./node_modules/windicss-webpack-plugin/dist/loaders/windicss-template.cjs
You may need an additional loader to handle the result of these loaders.
> <template>
|   <view class="index">
|     <NumberDisplay />

error Command failed with exit code 1.

请问还缺少哪个loader

**Comment by ItsRyanWu** [comment]
我目前未遇到这个问题，可以把你的代码上传上来让我看一下什么原因吗？

**Comment by PresByter2015** [comment]
已解决
按照  cli 和项目内部依赖版本一致； 并升级taro-cli版本
问题解决。
