### ISSUE TITLE
Windows10下使用mpx导入demo文件无效,./styles/virtual:windi-utilities23d5edd5.wxss文件未生成

### ISSUE THREAD

**Issue by Beyond-ordinary** [dcasia/mini-program-tailwind-webpack-plugin#4]
[ WXSS 文件编译错误] ./app.wxss
File not found: ./styles/virtual:windi-utilities23d5edd5.wxss(env: Windows,mp,1.05.2204180; lib: 2.23.4)
![image](https://user-images.githubusercontent.com/25141991/166252803-506f6606-5851-4c1a-a245-1a797af16a1d.png)

**Comment by ItsRyanWu** [comment]
通常情况下有两种原因
1. 未正确按照 Windi CSS 的官方教程正确安装了 WindiCSSWebpackPlugin
2. 未安装最新版的 MPX，历史版本的 MPX 有 bug
如果还是无法发现原因可以尝试跑一下[正常运行的 demo](https://github.com/dcasia/wechat-mini-program-tailwind/tree/development/examples/mpx) ，找一下差异

**Comment by ItsRyanWu** [comment]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/17338101/166619761-5fbf4b3d-8608-4490-8fe4-fc891634032d.png">
你那边是否有生成图中的样式文件？
另外你的 MPX 版本是多少？

**Comment by Beyond-ordinary** [comment]
> 

找到问题了 是windows下 生成的文件不允许包含" : " ，我修改了生成的源码后正常生成文件，  建议改成 “ - ”或其它符合

**Comment by Beyond-ordinary** [comment]
> <img alt="image" width="275" src="https://user-images.githubusercontent.com/17338101/166619761-5fbf4b3d-8608-4490-8fe4-fc891634032d.png">
> 
> 你那边是否有生成图中的样式文件？ 另外你的 MPX 版本是多少？

Windows不会生成的，文件名称有误不能带：

**Comment by ItsRyanWu** [comment]
> > 
> 
> 找到问题了 是windows下 生成的文件不允许包含" : " ，我修改了生成的源码后正常生成文件， 建议改成 “ - ”或其它符合

我了解了一下，这个应该是 Windi 应该是借鉴了 [Vite 的 virtual module ](https://vitejs.dev/guide/api-plugin.html#virtual-modules-convention)的命名方式将 virtual module 加上了前缀 'virtual:'，对于 Windows 用户的确不太友好。
这里也有一个相关 issue：https://github.com/windicss/windicss/issues/571

**Comment by ItsRyanWu** [comment]
https://github.com/windicss/windicss/issues/571

**Comment by perchecc** [comment]
> > 
> 
> 找到问题了 是windows下 生成的文件不允许包含" : " ，我修改了生成的源码后正常生成文件， 建议改成 “ - ”或其它符合

@Beyond-ordinary 请问生成的源码具体需要改动哪些，也遇到了同样问题，谢谢~

**Comment by Beyond-ordinary** [comment]
> > > 
> > 
> > 
> > 找到问题了 是windows下 生成的文件不允许包含" : " ，我修改了生成的源码后正常生成文件， 建议改成 “ - ”或其它符合
> 
> @Beyond-ordinary 请问生成的源码具体需要改动哪些，也遇到了同样问题，谢谢~

找一下node_modules里windicss-webpack-plugin的包好像,或者有需要我发一份给你邮箱

**Comment by perchecc** [comment]
> > > > 
> > > 
> > > 
> > > 找到问题了 是windows下 生成的文件不允许包含" : " ，我修改了生成的源码后正常生成文件， 建议改成 “ - ”或其它符合
> > 
> > 
> > @Beyond-ordinary 请问生成的源码具体需要改动哪些，也遇到了同样问题，谢谢~
> 
> 找一下node_modules里windicss-webpack-plugin的包好像,或者有需要我发一份给你邮箱

有需要的，谢谢啦 perchecc@163.com

**Comment by Beyond-ordinary** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 找到问题了 是windows下 生成的文件不允许包含" : " ，我修改了生成的源码后正常生成文件， 建议改成 “ - ”或其它符合
> > > 
> > > 
> > > @Beyond-ordinary 请问生成的源码具体需要改动哪些，也遇到了同样问题，谢谢~
> > 
> > 
> > 找一下node_modules里windicss-webpack-plugin的包好像,或者有需要我发一份给你邮箱
> 
> 有需要的，谢谢啦 [perchecc@163.com](mailto:perchecc@163.com)

已发送,替换这2个包试试
