### ISSUE TITLE
[BUG] Taro React 非pages目录失效

### ISSUE THREAD

**Issue by 3lang3** [dcasia/mini-program-tailwind-webpack-plugin#43]
只有**当前page中引入的**原子可以在其他目录生效

```jsx
// page/index/index.tsx
<View className="text-center mt-10">
  <Input />
</View>

// components/Input.tsx
<TaroInput className="mt-10 px-10" /> // 只有mt-10生效
```

**Comment by 3lang3** [comment]
@ItsRyanWu 很急，小伙伴写了一天page 刚准备写feature组件就gg了。。

**Comment by dhlolo** [comment]
> @ItsRyanWu 很急，小伙伴写了一天page 刚准备写feature组件就gg了。。

是不是没有设置[组件样式](https://github.com/dcasia/mini-program-tailwind#:~:text=%E6%88%91%E4%BB%AC%E9%9C%80%E8%A6%81%E5%9C%A8%E6%AF%8F%E4%B8%80%E4%B8%AA%E7%BB%84%E4%BB%B6%E7%9A%84%20JSON%20%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%B8%AD%E8%AE%BE%E7%BD%AE%E5%85%B6%E6%A0%B7%E5%BC%8F%E7%9A%84%E4%BD%9C%E7%94%A8%E5%9F%9F%20styleIsolation)"styleIsolation": "apply-shared"？
组件样式隔离[相关解释](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB:~:text=custom%2Dcomponent%3E-,%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB,-%E9%BB%98%E8%AE%A4%E6%83%85%E5%86%B5%E4%B8%8B)

**Comment by 3lang3** [comment]
> > @ItsRyanWu 很急，小伙伴写了一天page 刚准备写feature组件就gg了。。
> 
> 是不是没有设置[组件样式](https://github.com/dcasia/mini-program-tailwind#:~:text=%E6%88%91%E4%BB%AC%E9%9C%80%E8%A6%81%E5%9C%A8%E6%AF%8F%E4%B8%80%E4%B8%AA%E7%BB%84%E4%BB%B6%E7%9A%84%20JSON%20%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%B8%AD%E8%AE%BE%E7%BD%AE%E5%85%B6%E6%A0%B7%E5%BC%8F%E7%9A%84%E4%BD%9C%E7%94%A8%E5%9F%9F%20styleIsolation)"styleIsolation": "apply-shared"？
> 组件样式隔离[相关解释](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB:~:text=custom%2Dcomponent%3E-,%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB,-%E9%BB%98%E8%AE%A4%E6%83%85%E5%86%B5%E4%B8%8B)
> 

taro v3 react 已经没有样式隔离这个概念了，全部都是全局的，而且我设置了也不管用

**Comment by dhlolo** [comment]
> aro v3 react

感觉这个库主要还是这个小公司自己项目在用，有很多case是不支持的。<strike>很急的话可以试试自己写个postcss插件，在taro编译生成的每个组件的wxss文件中加入@import '/windi.wxss'</strike>这里我之前写的有问题，我只看了原生小程序的例子，taro刚看了一下，貌似是塞到了app.wxss中，没有检测出来的话应该是webpack-plugin文件中没有detect所有wxml文件

**Comment by 3lang3** [comment]
> > aro v3 react
> 
> 感觉这个库主要还是这个小公司自己项目在用，有很多case是不支持的。很急的话可以试试自己写个postcss插件，在taro编译生成的每个组件的wxss文件中加入@import '/windi.wxss'

那编译后会爆炸吗，我看了下，非pages下的原子类没有被收集到wxss里面去

**Comment by dhlolo** [comment]
> > > aro v3 react
> > 
> > 
> > 感觉这个库主要还是这个小公司自己项目在用，有很多case是不支持的。很急的话可以试试自己写个postcss插件，在taro编译生成的每个组件的wxss文件中加入@import '/windi.wxss'
> 
> 那编译后会爆炸吗，我看了下，非pages下的原子类没有被收集到wxss里面去

编译后爆炸啥意思？那有点麻烦了，盲猜是[这里](https://github.com/dcasia/mini-program-tailwind/blob/development/src/taro/wepack-plugin.ts#L57)拿到的module可能不全，或者只是页面的。
可以调试下看看

**Comment by 3lang3** [comment]
> > aro v3 react
> 
> 感觉这个库主要还是这个小公司自己项目在用，有很多case是不支持的。<strike>很急的话可以试试自己写个postcss插件，在taro编译生成的每个组件的wxss文件中加入@import '/windi.wxss'</strike>这里我之前写的有问题，我只看了原生小程序的例子，taro刚看了一下，貌似是塞到了app.wxss中，没有检测出来的话应该是webpack-plugin文件中没有detect所有wxml文件

兄弟 想办法搞个pr？

**Comment by dhlolo** [comment]
> > > aro v3 react
> > 
> > 
> > 感觉这个库主要还是这个小公司自己项目在用，有很多case是不支持的。很急的话可以试试自己写个postcss插件，在taro编译生成的每个组件的wxss文件中加入@import '/windi.wxss'这里我之前写的有问题，我只看了原生小程序的例子，taro刚看了一下，貌似是塞到了app.wxss中，没有检测出来的话应该是webpack-plugin文件中没有detect所有wxml文件
> 
> 兄弟 想办法搞个pr？

用他这个的库的taro样例[试了下](https://github.com/dhlolo/mini-program-tailwind/tree/feat/test)，detect到了，渲染也没问题。。应该是你项目中的一些配置或者taro编译和样例不一样？

**Comment by 3lang3** [comment]
> > > > aro v3 react
> > > 
> > > 
> > > 感觉这个库主要还是这个小公司自己项目在用，有很多case是不支持的。很急的话可以试试自己写个postcss插件，在taro编译生成的每个组件的wxss文件中加入@import '/windi.wxss'这里我之前写的有问题，我只看了原生小程序的例子，taro刚看了一下，貌似是塞到了app.wxss中，没有检测出来的话应该是webpack-plugin文件中没有detect所有wxml文件
> > 
> > 
> > 兄弟 想办法搞个pr？
> 
> 用他这个的库的taro样例[试了下](https://github.com/dhlolo/mini-program-tailwind/tree/feat/test)，detect到了，渲染也没问题。。应该是你项目中的一些配置或者taro编译和样例不一样？

。。我是改了下配置，我clone个demo试试

**Comment by 3lang3** [comment]
> > > > aro v3 react
> > > 
> > > 
> > > 感觉这个库主要还是这个小公司自己项目在用，有很多case是不支持的。很急的话可以试试自己写个postcss插件，在taro编译生成的每个组件的wxss文件中加入@import '/windi.wxss'这里我之前写的有问题，我只看了原生小程序的例子，taro刚看了一下，貌似是塞到了app.wxss中，没有检测出来的话应该是webpack-plugin文件中没有detect所有wxml文件
> > 
> > 
> > 兄弟 想办法搞个pr？
> 
> 用他这个的库的taro样例[试了下](https://github.com/dhlolo/mini-program-tailwind/tree/feat/test)，detect到了，渲染也没问题。。应该是你项目中的一些配置或者taro编译和样例不一样？

我配置问题
```js
// windi.config.js
export default {
  prefixer: false,
  extract: {
    include:  // 这里配错了
  },
  corePlugins: {
    // 禁用掉在小程序环境中不可能用到的 plugins
    container: false
  }
}
```

@dhlolo  谢了 哥们~

**Comment by ItsRyanWu** [comment]
刚到家打算研究一下，看来已经不用了...
以后有问题欢迎再提 Issue
