### ISSUE TITLE
Taro rem 没有转为 rpx

### ISSUE THREAD

**Issue by Sean529** [dcasia/mini-program-tailwind-webpack-plugin#46]

**Comment by Sean529** [comment]
<img width="178" alt="image" src="https://user-images.githubusercontent.com/17820508/181705288-64106d3e-a790-4a15-831c-65f2fd4a6841.png">

**Comment by Sean529** [comment]
```
<View className='text-xs'>title</View>
```
![image](https://user-images.githubusercontent.com/17820508/181705467-ba928e5b-22fb-4e70-a800-123bf2785bca.png)

**Comment by ItsRyanWu** [comment]
插件自身的 `enableRpx` 功能默认是关闭的，如需开启请声明：
```javascript
plugins: [
  ['@dcasia/mini-program-tailwind-webpack-plugin/dist/taro', {
    enableRpx: true
  }]
]
```
需要注意的是虽然 Taro 自带 px to rpx 的转换功能但是他是无法将 rem 转换成 rpx 的，要实现这一功能需要将 Taro 的转换功能关闭然后启用插件的转换。

**Comment by Sean529** [comment]
感谢大神，请问怎么关闭 Taro px to rpx。另外关闭 Taro 的 px to rpx 会不会对项目有其他影响。

**Comment by Sean529** [comment]
@ItsRyanWu 

> 插件本身的`enableRpx`功能默认是关闭的，如需开启请声明：
> 
> ```js
> plugins: [
>   ['@dcasia/mini-program-tailwind-webpack-plugin/dist/taro', {
>     enableRpx: true
>   }]
> ]
> ```
> 
> 注意的是虽然 Taro 需要自带 px 到 rpx 的转换但功能他是无法将 rem 转换成 rpx 的，然后要实现这一功能需要将 Taro 的转换功能启用插件的转换。


感谢大神，请问怎么关闭 Taro px to rpx。另外关闭 Taro 的 px to rpx 会对项目有其他影响吗。

**Comment by Sean529** [comment]
> 插件自身的 `enableRpx` 功能默认是关闭的，如需开启请声明：
> 
> ```js
> plugins: [
>   ['@dcasia/mini-program-tailwind-webpack-plugin/dist/taro', {
>     enableRpx: true
>   }]
> ]
> ```
> 
> 需要注意的是虽然 Taro 自带 px to rpx 的转换功能但是他是无法将 rem 转换成 rpx 的，要实现这一功能需要将 Taro 的转换功能关闭然后启用插件的转换。

😄 尝试后发现直接设置插件的 enableRpx: true 就可以将 rem 转为 rpx 了，
不用再另外关闭 Taro 的 px to rpx。

**Comment by ItsRyanWu** [comment]
对，当然是可以的，只不过从节省编译性能的角度考虑最好可以把 Taro 的转换关掉，因为功能是部分重叠的。

**Comment by Sean529** [comment]
> 对，当然是可以的，只不过从节省编译性能的角度考虑最好可以把 Taro 的转换关掉，因为功能是部分重叠的。

大佬，请教下怎么关闭 Taro 自带的 px2rpx，找了很久没有找到相关资料。Taro 官网的配置中也没有相关 API。
