### ISSUE TITLE
rem 与 px 单位 转换rpx  用户如何自定义设置比例呢？

### ISSUE THREAD

**Issue by HHH917** [dcasia/mini-program-tailwind-webpack-plugin#49]
rem 与 px 单位的值在最终生成的样式文件中自动转换为 rpx 单位  这个转换比例用户如何自定义设置呢？

**Comment by ItsRyanWu** [comment]
文档中有提到 `designWidth` 这个选项，这个选项的设计原因是目前大部分设计还是以 iPhone 375px 逻辑像素为宽度的，如果你参考的设计就是以 375px 为宽度，那么填入 `375` 的转换比例就是 `1px === 2rpx`。如果你参考的设计是 750px 宽度，那么填入 750 后的转换比例就是 `1px === 1rpx`。
