### ISSUE TITLE
请问这个插件能用于taro转h5和百度小程序吗

### ISSUE THREAD

**Issue by bluescurry** [dcasia/mini-program-tailwind-webpack-plugin#51]

**Comment by ItsRyanWu** [comment]
当用 Taro 转 H5 时，插件功能自动关闭，因为 H5 的环境和 Web 标准一致，不需要该插件工作。
至于转百度小程序的话题，代码中是提前做了文件后缀的兼容性处理的，只是目前我还没收到其他开发者有关百度小程序反馈，如果你在使用过程中遇到问题的话，也欢迎你来反馈。
