### ISSUE TITLE
after或before伪元素的content有限制

### ISSUE THREAD

**Issue by riverside0** [dcasia/mini-program-tailwind-webpack-plugin#54]
![image](https://user-images.githubusercontent.com/50392862/183369200-fe816a5f-d1ea-4566-9c26-899c59c0116f.png)
这样是没法编译的，只能是
![image](https://user-images.githubusercontent.com/50392862/183369598-4b885b0f-3573-4b66-a059-392fa12abc1a.png)
这样就没法处理content是中文或其他字符的情况了

**Comment by ItsRyanWu** [comment]
兼容 `'` 是很简单的，问题是经过测试后我发现 Windi CSS 对于 Pseudo Element Content 本身就不兼容中文，也不兼容图 1 中的单引号写法，这些都是无法生成对应的 CSS 样式的，它只兼容 `after:content-1234`, `after:content-[1234]`  这种写法。
无论怎样我都会在下个版本中补全对于 `'` 的兼容，以防其他情况会用到。
