### ISSUE TITLE
rpx支持有局限？还是我的配置不正确？

### ISSUE THREAD

**Issue by zhtyytg** [dcasia/mini-program-tailwind-webpack-plugin#56]
![image](https://user-images.githubusercontent.com/42018740/183784003-1a7f7704-75bb-4493-8afb-618aa1ce164f.png)
![image](https://user-images.githubusercontent.com/42018740/183784098-b51ea916-3db5-430f-95a6-2ac14cdf4d49.png)

在chrome移动端模拟下，配置了开启rpx，编译结果仍然是rem

**Comment by ItsRyanWu** [comment]
Chrome 移动端的 H5 应用？在编译 H5 应用时 rpx 转换自动关闭，因为 H5 没有 rpx。

**Comment by zhtyytg** [comment]
> Chrome 移动端的 H5 应用？在编译 H5 应用时 rpx 转换自动关闭，因为 H5 没有 rpx。

感谢答疑
uniapp内置的rpx编译，习惯后有些魔怔了
