### ISSUE TITLE
在macOS上出现的类名错误

### ISSUE THREAD

**Issue by Truimo** [dcasia/mini-program-tailwind-webpack-plugin#57]
macOS m1
node 16.16.0
@tarojs/cli 3.5.1
@dcasia/mini-program-tailwind-webpack-plugin ^1.5.1

出现`top-1/2`(1)分数区域的斜杠在页面中的class里变成`top-1 2`(2)，编译出来的css中还是包含`top-1-s-2`的，在Windows中(3)开发时正常。
![code](https://xxgame-oss-1305181693.file.myqcloud.com/im/60878/95528232_1660405330.png)
生成的
![code](https://xxgame-oss-1305181693.file.myqcloud.com/im/60878/58696516_1660405509.png)
[截图1](https://xxgame-oss-1305181693.file.myqcloud.com/im/60878/95528232_1660405330.png)  [截图2](https://xxgame-oss-1305181693.file.myqcloud.com/im/60878/58696516_1660405509.png)  [截图3](https://xxgame-oss-1305181693.file.myqcloud.com/im/60878/55107975_1660405581.png)

**Comment by ItsRyanWu** [comment]
请问在 Windows 系统下的正常情况中你的 Taro 也是 3.5 版本吗？能否上传一个可复现 repo 让我看一下，我平时也是用 macOS 做开发的。

**Comment by ItsRyanWu** [comment]
插件的 `1.5.1` 版本并未兼容 Taro 3.5 但是 `1.5.2` 版本是兼容的，所以请升级来获取修复。
Issue 和 macOS 无关。
