### ISSUE TITLE
Taro vue3 使用typescript时特殊字符未转义

### ISSUE THREAD

**Issue by tyuan511** [dcasia/mini-program-tailwind-webpack-plugin#59]
在使用vue3 setup script时，将lang设成ts会导致特殊字符无法转义
只有build模式下有这个问题，dev时没有
![image](https://user-images.githubusercontent.com/15307345/184616715-7080f70b-2b43-40cf-a853-7c4044e7f3ef.png)
<img width="469" alt="image" src="https://user-images.githubusercontent.com/15307345/184616802-02eee347-887a-4b60-b86f-93ecd9a3c308.png">

taro版本：3.5.2 
@dcasia/mini-program-tailwind-webpack-plugin版本： 1.5.3

最小重现demo: https://github.com/tyuan511/taro-tailwind-demo

**Comment by tyuan511** [comment]
发现 `<script lang="ts" setup>`会解析成`type=script&lang=ts&setup=true`， 然后`module?.resource?.includes('type=script&setup=true')`就匹配不上了，把标签写成`<script setup lang="ts">`就可以了
感觉最好是能去解析下resource的querystring再去匹配能精准点

**Comment by ItsRyanWu** [comment]
> 发现 `<script lang="ts" setup>`会解析成`type=script&lang=ts&setup=true`， 然后`module?.resource?.includes('type=script&setup=true')`就匹配不上了，把标签写成`<script setup lang="ts">`就可以了 感觉最好是能去解析下resource的querystring再去匹配能精准点

感谢你的反馈，我近两天更新一下。
