### ISSUE TITLE
在wx小程序里不支持自定义font family

### ISSUE THREAD

**Issue by riverside0** [dcasia/mini-program-tailwind-webpack-plugin#65]
![image](https://user-images.githubusercontent.com/50392862/186122155-54123246-ef69-467d-95a2-8fdb0b6e2404.png)
zh这样会把中括号里的"编译成空格
![image](https://user-images.githubusercontent.com/50392862/186122364-2c19e689-175b-4701-a31c-c2285cda7e0b.png)
虽然可以通过自定义语法解决 但是还是希望支持一下这个能力
![image](https://user-images.githubusercontent.com/50392862/186123652-d481c9d0-c2fa-4f19-90c2-92d37b73ae83.png)

**Comment by ItsRyanWu** [comment]
经过测试发现 Windi CSS 不支持直接在 class name 里书写 font family，所以目前插件即使支持这种写法最终也不会生成样式。
