### ISSUE TITLE
在 Taro 下 H5 与小程序端样式大小不一

### ISSUE THREAD

**Issue by neyric** [dcasia/mini-program-tailwind-webpack-plugin#86]
使用 Taro 开发，插件在 MiniProgram 端表现正常，**运行在 H5 端样式出现错误。**

推测原因是：**H5 端的 html 标签上，taro 根据页面尺寸，动态应用了一个 font-size 尺寸**。同时插件也根据页面尺寸，计算了 rem 出来。导致在 h5 上产生了重复的应用。

**Comment by coderlfm** [comment]
我遇到了一样的问题，
小程序端：
`w-4 -> 8px`，
`w-[16px] -> 8px`,
在h5端设置成根字体大小是16px后
**`w-4 -> 1rem(16px)`**
`w-[16px] -> 0.5rem(8px)`

**Comment by BJ4501** [comment]
可以在 `postcss.pxtransform` 中控制根节点font-size的值
```
baseFontSize: 20,
maxRootSize: 40,
minRootSize: 20
```
参考文档：https://docs.taro.zone/docs/size/
