### ISSUE TITLE
使用模板字符串换行后，生成的类名有误导致样式不正确

### ISSUE THREAD

**Issue by RunningCoderLee** [dcasia/mini-program-tailwind-webpack-plugin#97]
比如写成这种样式的类型 

```tsx
<View
  className={`p-4 bg-red-400 text-[40px]
h-4`}
>
  12312312
</View>
```

<img width="439" alt="image" src="https://user-images.githubusercontent.com/13218863/230558513-fa3f8411-206d-4835-a275-b85c4a8973f8.png">

![image](https://user-images.githubusercontent.com/13218863/230558759-18c1d774-a73f-4244-9660-f610c0521890.png)

**Comment by zxqzy** [comment]
我也遇到这个问题了，我发现只是初次不生效，watch 的时候能够生效，现在问题解决了吗

**Comment by zxqzy** [comment]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/37129846/232947161-21fca232-c7ec-4143-af0f-6c28775a93b3.png">
<img width="801" alt="image" src="https://user-images.githubusercontent.com/37129846/232947204-431d6717-0ac0-48af-9320-8ba55e97b31b.png">
不换行也会出问题

**Comment by RunningCoderLee** [comment]
没解决，持续观望中ing。。。

**Comment by ItsRyanWu** [comment]
请升级至 `1.5.7-beta.0` 试试看呢？如果没有问题我就发布正式版了
